- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - puppet-openstack-litmus-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-keystone-tripleo-standalone

- job:
    name: puppet-keystone-tripleo-standalone
    parent: tripleo-puppet-ci-centos-9-standalone
    description: |
      TripleO standalone Job running Identity specific Tempest tests.
    voting: false
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.api.identity.v3'
        use_os_tempest: true
