name    'puppetlabs-keystone'
version '1.0.1'
source  'git://github.com/puppetlabs/puppetlabs-keystone'
author  'Puppet Labs'
license 'Apache'
summary 'Keystone Puppet Module'
description 'Openstack Folsom Keystone module. Tested on Ubuntu and RHEL 6'
project_page 'http://github.com/puppetlabs/puppetlabs-keystone'

dependency 'cprice404/inifile', '>= 0.9.0'
dependency 'puppetlabs/mysql', '>= 0.5.0'
