name         'puppetlabs-keystone'
version      '4.0.0'
author       'Puppet Labs and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Keystone'
description  'Installs and configures OpenStack Keystone (Identity).'
project_page 'https://launchpad.net/puppet-keystone'
source       'https://github.com/stackforge/puppet-keystone'

dependency 'puppetlabs/apache', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
